version: '3'
services:
    dnsmasq:
        build: .
        image: xyzrlee/dnsmasq
        restart: unless-stopped
        ports:
            - "5353:53/tcp"
            - "5353:53/udp"
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/conf:ro
        command: --conf-file=/conf/dnsmasq.conf --log-facility=/dev/stdout
