version: '3'
services:
    dnsmasq:
        build: .
        image: xyzrlee/dnsmasq
        restart: unless-stopped
        ports:
            - "5353:53/tcp"
            - "5353:53/udp"
        cap_add:
            - NET_ADMIN
        volumes:
            - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
        command: --log-facility=/dev/stdout
